---
- name: Deploy ML Services
  hosts: localhost
  tasks:
    - name: Start Minikube with custom IP
      shell: |
        minikube stop || true
        minikube start --extra-config=kubelet.node-ip=192.168.49.2 --apiserver-ips=192.168.49.2

    - name: Configure kubectl context for Minikube
      shell: |
        kubectl config use-context minikube
        kubectl cluster-info

    - name: Deploy ml-service
      shell: |
        kubectl apply -f main1/ml-service.yaml
        kubectl expose deployment ml-service --type=NodePort --name=ml-service-exposed

    - name: Deploy ml-service2
      shell: |
        kubectl apply -f main2/ml-service2.yaml
        kubectl expose deployment ml-service2 --type=NodePort --name=ml-service2-exposed

    - name: Wait for Pods to be Ready
      shell: kubectl wait --for=condition=ready pod --all
